package pihole

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sync"
)

// SafeSearchManager manages deterministic VIP injection for Google, YouTube, Bing, DuckDuckGo.
type SafeSearchManager struct {
	ConfigPath string
	mu         sync.RWMutex
	enabled    bool
}

// NewSafeSearchManager initializes the SafeSearch manager.
func NewSafeSearchManager(configPath string) *SafeSearchManager {
	if configPath == "" {
		configPath = "/etc/dnsmasq.d/05-safesearch.conf"
	}
	m := &SafeSearchManager{
		ConfigPath: configPath,
		enabled:    true,
	}
	_ = m.Apply(context.Background())
	return m
}

// Apply writes CNAME VIP redirection rules.
func (m *SafeSearchManager) Apply(ctx context.Context) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	if !m.enabled {
		_ = os.Remove(m.ConfigPath)
		m.reloadDNS(ctx)
		return nil
	}

	content := `# Aegis Deterministic SafeSearch & Parental Restriction CNAME Injection
# Auto-generated by Aegis Sentinel. Do not edit manually.

# 1. Google SafeSearch VIP
cname=google.com,forcesafesearch.google.com
cname=www.google.com,forcesafesearch.google.com
cname=google.com.ph,forcesafesearch.google.com
cname=www.google.com.ph,forcesafesearch.google.com

# 2. YouTube Restricted Mode
cname=youtube.com,restrictmoderate.youtube.com
cname=www.youtube.com,restrictmoderate.youtube.com
cname=m.youtube.com,restrictmoderate.youtube.com
cname=youtubei.googleapis.com,restrictmoderate.youtube.com

# 3. Bing Strict SafeSearch
cname=bing.com,strict.bing.com
cname=www.bing.com,strict.bing.com

# 4. DuckDuckGo SafeSearch
cname=duckduckgo.com,safe.duckduckgo.com
`
	_ = os.MkdirAll(filepath.Dir(m.ConfigPath), 0755)
	if err := os.WriteFile(m.ConfigPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write safesearch config: %w", err)
	}

	m.reloadDNS(ctx)
	return nil
}

// Toggle flips SafeSearch status.
func (m *SafeSearchManager) Toggle(ctx context.Context, enabled bool) error {
	m.enabled = enabled
	return m.Apply(ctx)
}

func (m *SafeSearchManager) reloadDNS(ctx context.Context) {
	if path, err := exec.LookPath("pihole"); err == nil {
		_ = exec.CommandContext(ctx, path, "restartdns", "reload").Run()
	}
}

// GetStatus returns the current status.
func (m *SafeSearchManager) GetStatus() map[string]interface{} {
	m.mu.RLock()
	defer m.mu.RUnlock()

	return map[string]interface{}{
		"enabled":            m.enabled,
		"enforce_google":     m.enabled,
		"enforce_youtube":    m.enabled,
		"enforce_bing":       m.enabled,
		"enforce_duckduckgo": m.enabled,
	}
}
